# Generated by Django 4.1.7 on 2023-04-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roomBooking", "0004_remove_reservation_end_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
