# Generated by Django 4.1.7 on 2023-04-30 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roomBooking", "0005_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="end_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
