# Generated by Django 4.1.7 on 2023-05-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roomBooking", "0007_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="availability",
            field=models.JSONField(default=dict),
        ),
    ]
